# Generated by Django 5.2.7 on 2025-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='type',
            field=models.CharField(choices=[('tutorials', 'آموزشی'), ('news', 'اخبار'), ('workshop', 'فعالیت های مجموعه'), ('product_videos', 'معرفی محصولات')], max_length=30, unique=True),
        ),
    ]
