# Generated by Django 6.0.2 on 2026-02-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcode_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
