# Generated by Django 6.0.2 on 2026-04-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
