# Generated by Django 6.0.2 on 2026-04-22 21:38

import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('shipping_method', models.CharField(choices=[('pishtaz', 'پست پیشتاز'), ('in_person', 'تحویل حضوری')], default='pishtaz', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_code', models.PositiveIntegerField(db_index=True, default=orders.models.generate_order_code, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('shipping_price', models.PositiveBigIntegerField(default=0)),
                ('discount_amount', models.PositiveBigIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('waiting', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='waiting', max_length=15)),
                ('order_status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_ref_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.PositiveBigIntegerField(blank=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('order', 'product_type', 'product_id')},
            },
        ),
    ]
