# Generated by Django 6.0.2 on 2026-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pishtaz', 'پست پیشتاز'), ('in_person', 'تحویل حضوری'), ('Barbari', 'شرکت های باربری')], default='in_person', max_length=20),
        ),
    ]
