# Generated by Django 6.0.2 on 2026-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
