# Generated by Django 6.0.2 on 2026-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method_label',
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percent',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='waiting', max_length=20),
        ),
    ]
