# Generated by Django 5.2.7 on 2025-10-22 17:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('old_price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی')),
                ('offer_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت با تخفیف')),
                ('off_percent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصدتخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_offer', models.BooleanField(default=False, verbose_name='پیشنهادی')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('most_selling', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, default='Transistor', max_length=100, null=True, verbose_name='نوع امپ')),
                ('watt', models.CharField(blank=True, max_length=100, null=True, verbose_name='وات')),
                ('panel_screw', models.CharField(blank=True, max_length=100, null=True, verbose_name='تعداد پیچ تنظیم')),
                ('channel_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='تعداد کانال\u200cها')),
                ('input', models.CharField(blank=True, max_length=50, null=True, verbose_name='ورودی')),
                ('output', models.CharField(blank=True, max_length=50, null=True, verbose_name='خروجی')),
                ('headphone_output', models.BooleanField(default=False, verbose_name='خروجی هدفن')),
                ('guaranty', models.BooleanField(blank=True, default=False, null=True, verbose_name='گارانتی ۲۴ماهه')),
            ],
            options={
                'verbose_name': 'AMP',
                'verbose_name_plural': 'AMP',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('old_price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی')),
                ('offer_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت با تخفیف')),
                ('off_percent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصدتخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_offer', models.BooleanField(default=False, verbose_name='پیشنهادی')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('most_selling', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clp_series', models.CharField(blank=True, choices=[('EX', 'EX'), ('LS', 'LS'), ('S', 'S')], max_length=20, null=True, verbose_name='سری گیتار')),
                ('body_material', models.CharField(blank=True, choices=[('plywood', 'plywood'), ('solid_wood', 'solid_wood'), ('resin_epoxy', 'resin_epoxy')], max_length=20, null=True, verbose_name='جنس بدنه')),
                ('stick_wood_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس دسته')),
                ('fingerboard_wood_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس فینگربرد')),
                ('frets_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد فرت\u200cها')),
                ('selector_mode', models.CharField(blank=True, max_length=100, null=True, verbose_name='سلکتور')),
                ('bridge', models.CharField(blank=True, max_length=100, null=True, verbose_name='بریج')),
                ('pickup_types', models.CharField(blank=True, max_length=100, null=True, verbose_name='پیکاپ')),
                ('guaranty', models.BooleanField(blank=True, default=False, null=True, verbose_name='گارانتی ۲۴ماهه')),
            ],
            options={
                'verbose_name': 'CLP',
                'verbose_name_plural': 'CLP',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('old_price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی')),
                ('offer_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت با تخفیف')),
                ('off_percent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصدتخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_offer', models.BooleanField(default=False, verbose_name='پیشنهادی')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('most_selling', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_series', models.CharField(choices=[('body', 'Body'), ('bridge', 'Bridge'), ('saddle', 'Saddle'), ('pickup', 'Pickup'), ('selector', 'Selector'), ('potentiometer', 'Potentiometer'), ('nub_volume', 'Nub Volume'), ('output_jack', 'Output_Jack'), ('neck', 'Neck'), ('fret', 'Fret'), ('fingerboard', 'Fingerboard'), ('tuning_pegs', 'Tuning Pegs'), ('neck_screw', 'Neck_Screw'), ('truss_rod', 'Truss Rod'), ('strap', 'Strap'), ('pin_strap', 'pin_strap'), ('pick', 'Pick'), ('stand', 'Stand'), ('cleaner', 'Cleaner'), ('metronome', 'Metronome'), ('cable', 'Cable'), ('capo', 'Capo'), ('nut', 'Nut')], max_length=40, verbose_name='سری لوازم\u200cجانبی')),
                ('neck_type', models.CharField(blank=True, choices=[('fretless', 'Fretless'), ('fretted', 'Fretted')], default=None, max_length=30, null=True, verbose_name='نوع دسته')),
                ('fret_type', models.CharField(blank=True, choices=[('cutted', 'Cutted'), ('metric', 'Metric')], max_length=20, null=True, verbose_name='نوع فرت')),
                ('brand', models.CharField(blank=True, max_length=40, null=True, verbose_name='برند')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GuitarStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('old_price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی')),
                ('offer_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت با تخفیف')),
                ('off_percent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصدتخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_offer', models.BooleanField(default=False, verbose_name='پیشنهادی')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('most_selling', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('string_type', models.CharField(choices=[('classic', 'Classic'), ('acoustic', 'Acoustic'), ('electric', 'Electric')], max_length=30, verbose_name='نوع ساز')),
                ('tension', models.CharField(blank=True, choices=[('hard', 'Hard'), ('normal', 'Normal'), ('soft', 'Soft'), ('10-47', '10-47'), ('11-52', '11-52'), ('12-54', '12-54'), ('10-46', '10-46'), ('9-42', '9-42')], max_length=30, null=True, verbose_name='سایز سیم')),
                ('brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='برند')),
            ],
            options={
                'verbose_name': 'GuitarStrings',
                'verbose_name_plural': 'GuitarStrings',
                'ordering': ('-created_at', 'tension'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/images/alt_img')),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
