# Generated by Django 5.2.7 on 2025-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarstrings',
            name='tension',
            field=models.CharField(blank=True, choices=[('hard', 'Hard'), ('normal', 'Normal'), ('soft', 'Soft'), ('10-47', '10-47'), ('11-52', '11-52'), ('12-54', '12-54'), ('10-46', '10-46'), ('9-42', '9-42'), ('11-48', '11-48'), ('12-56', '12-56'), ('10-52', '10-52'), ('9-46', '9-46'), ('11-54', '11-54')], max_length=30, null=True, verbose_name='سایز سیم'),
        ),
    ]
