# Generated by Django 6.0.2 on 2026-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_guitarstrings_tension'),
    ]

    operations = [
        migrations.AddField(
            model_name='amp',
            name='amp_series',
            field=models.CharField(blank=True, choices=[('10W', '10W'), ('20W', '20W')], max_length=10, null=True, verbose_name='نوع امپ'),
        ),
        migrations.AlterField(
            model_name='clp',
            name='body_material',
            field=models.CharField(blank=True, choices=[('Poly Wood', 'Poly Wood'), ('Solid Wood', 'Solid Wood'), ('Epoxy Wood', 'Epoxy Wood')], max_length=20, null=True, verbose_name='جنس بدنه'),
        ),
        migrations.AlterField(
            model_name='clp',
            name='clp_series',
            field=models.CharField(blank=True, choices=[('Explorer', 'Explorer'), ('Les Paul', 'Les Paul'), ('Stratocaster', 'Stratocaster')], max_length=20, null=True, verbose_name='سری گیتار'),
        ),
    ]
