# Generated by Django 6.0.2 on 2026-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_amp_amp_series_alter_clp_body_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clp',
            name='body_material',
            field=models.CharField(blank=True, choices=[('Poly_Wood', 'Poly_Wood'), ('Solid_Wood', 'Solid_Wood'), ('Epoxy_Wood', 'Epoxy_Wood')], max_length=20, null=True, verbose_name='جنس بدنه'),
        ),
        migrations.AlterField(
            model_name='clp',
            name='clp_series',
            field=models.CharField(blank=True, choices=[('Explorer', 'Explorer'), ('Les Paul', 'Les Paul'), ('Stratocaster', 'Stratocaster'), ('Star-X', 'Start-X'), ('Warlock', 'Warlock')], max_length=20, null=True, verbose_name='سری گیتار'),
        ),
    ]
