# Generated by Django 6.0.2 on 2026-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_clp_body_material_alter_clp_clp_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clp',
            name='clp_series',
            field=models.CharField(blank=True, choices=[('Explorer', 'EX'), ('Les Paul', 'LS'), ('Stratocaster', 'S'), ('Star-X', 'Star-X'), ('Warlock', 'Warlock')], max_length=20, null=True, verbose_name='سری گیتار'),
        ),
    ]
