# Generated by Django 6.0.2 on 2026-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_clp_clp_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clp',
            name='clp_series',
            field=models.CharField(blank=True, choices=[('EX', 'Explorer'), ('LS', 'Les Paul Standard'), ('S', 'Stratocaster'), ('Star-X', 'Star-X'), ('Warlock', 'Warlock')], max_length=20, null=True, verbose_name='سری گیتار'),
        ),
    ]
